language: ruby
dist: trusty
sudo: false
cache: bundler
bundler_args: --without tools benchmarks
script:
  - bundle exec rake
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - jruby-9.1.5.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
addons:
  code_climate:
    repo_token: c1c8f334714254acf5da901ca4da6afe24b15408074faae27159e3d14a450b62
