language: ruby
dist: trusty
sudo: false
cache: bundler
bundler_args: --without tools benchmarks
before_install:
  - gem update --system
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.13.7
script:
  - bundle exec rake
after_success:
    # Send coverage report from the job #1 == current MRI release
  - '[ "${TRAVIS_JOB_NUMBER#*.}" = "1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - jruby-9.1.6.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: jruby-9.1.6.0
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
addons:
  code_climate:
    repo_token: c1c8f334714254acf5da901ca4da6afe24b15408074faae27159e3d14a450b62
