language: ruby
script: 'bundle exec rake test:coverage'
sudo: false
cache: bundler
install: true
env:
  global:
    - JRUBY_OPTS=--dev
script:
  - 'if [[ "$TRAVIS_RUBY_VERSION" =~ "jruby" ]]; then rvm get head && rvm reload && rvm use --install $TRAVIS_RUBY_VERSION; fi'
  - 'bundle install'
  - 'bundle exec rake test:coverage'
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.1.6
  - 2.1.7
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - jruby-9000
  - jruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
